### ISSUE TITLE
strict mode

### ISSUE THREAD

**Issue by andcastillo** [mljs/sparse-matrix#2]
@targos can you declare the SparseMatrix.js in strict mode. I'm having this error while trying to run the tests in a related lib:
```
/git/spectra-data/node_modules/ml-sparse-matrix/src/SparseMatrix.js:3
class SparseMatrix {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/acastillo/git/spectra-data/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:355:32)
```

**Comment by targos** [comment]
done, but try to update your node. I think it is supported now
